# Generated by Django 4.2 on 2023-04-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_options_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name', 'parent__id', 'id']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='named_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
